"""
Feature engineering for time-series ATM cash demand forecasting.
Extracts calendar cyclical patterns, banking salary surge indicators,
autoregressive lags, and strictly non-leaking rolling window statistics.
"""

import numpy as np
import pandas as pd
from typing import Tuple, List


def create_features(
    df: pd.DataFrame,
    target_col: str = "Value",
    lags: List[int] = (1, 2, 3, 7, 14),
    rolling_windows: List[int] = (7, 14),
    include_holidays: bool = True
) -> Tuple[pd.DataFrame, pd.Series, List[str]]:
    """
    Constructs an ML-ready tabular feature matrix from a time-series DataFrame with DatetimeIndex.
    
    Guarantees strict featurization hygiene:
    - Rolling calculations are applied ONLY on lagged values (shift(1)) to prevent lookahead leakage.
    - Calendar cyclical features preserve continuous circular topology for linear and tree models.
    """
    df_feat = df.copy()

    # Ensure target is numeric
    df_feat[target_col] = pd.to_numeric(df_feat[target_col], errors="coerce")

    # 1. Calendar & Business Day Features
    dt = df_feat.index
    df_feat["day_of_week"] = dt.dayofweek
    df_feat["day_of_month"] = dt.day
    df_feat["month"] = dt.month
    df_feat["is_weekend"] = (dt.dayofweek >= 5).astype(int)
    
    # Banking specific: Salary / pension disbursement surge (1st to 5th of each month)
    df_feat["is_salary_day"] = ((dt.day >= 1) & (dt.day <= 5)).astype(int)
    df_feat["is_month_start"] = (dt.day <= 3).astype(int)
    df_feat["is_month_end"] = (dt.day >= 26).astype(int)

    # Cyclical encodings
    df_feat["sin_dow"] = np.sin(2 * np.pi * dt.dayofweek / 7.0)
    df_feat["cos_dow"] = np.cos(2 * np.pi * dt.dayofweek / 7.0)
    df_feat["sin_month"] = np.sin(2 * np.pi * dt.month / 12.0)
    df_feat["cos_month"] = np.cos(2 * np.pi * dt.month / 12.0)

    # Optional Holiday Indicator (from network dataset if present)
    if include_holidays and "Holiday_Flag" in df_feat.columns:
        df_feat["is_holiday"] = df_feat["Holiday_Flag"].fillna(0).astype(int)

    # 2. Autoregressive Lags (t-1, t-2, t-3, t-7, t-14)
    for lag in lags:
        df_feat[f"lag_{lag}"] = df_feat[target_col].shift(lag)

    # 3. Rolling Window Statistics (Strictly shifted by 1 to prevent lookahead leakage)
    for w in rolling_windows:
        shifted = df_feat[target_col].shift(1)
        df_feat[f"rolling_mean_{w}"] = shifted.rolling(window=w).mean()
        df_feat[f"rolling_std_{w}"] = shifted.rolling(window=w).std()
        df_feat[f"rolling_min_{w}"] = shifted.rolling(window=w).min()
        df_feat[f"rolling_max_{w}"] = shifted.rolling(window=w).max()

    # Drop intermediate or non-feature text columns if present
    drop_cols = [col for col in ["ATM_ID", "ATM_Name", "Location_Type", "Holiday_Name", "Avg_Ticket_Size", "Day_Of_Week", "Transaction_Count", "Holiday_Flag", "Capacity", "Cash_Withdrawn"] if col in df_feat.columns]
    df_feat = df_feat.drop(columns=drop_cols)

    # Drop NaN rows generated by initial lags
    df_feat = df_feat.dropna()

    y = df_feat[target_col]
    X = df_feat.drop(columns=[target_col])
    feature_names = X.columns.tolist()

    return X, y, feature_names
